from backend.models import Template


class Messages():
    MESSAGE = Template.messages.get(id=1).gettext()
    START_COMMAND = Template.messages.get(id=4).gettext()
    WANT_REG = Template.messages.get(id=6).gettext()
    INPUT_NAME = Template.messages.get(id=9).gettext()
    REG_FINISH = Template.messages.get(id=10).gettext()
    CONTACTS = Template.messages.get(id=27).gettext()
    SELECT_REGION = Template.messages.get(id=33).gettext()
    RESERVATION = Template.messages.get(id=37).gettext()
    RESERVATION_TIME = Template.messages.get(id=42).gettext()
    CANT_TODAY = Template.messages.get(id=43).gettext()
    INCORRECT_TIME = Template.messages.get(id=44).gettext()
    WORKING_TIME_ERROR = Template.messages.get(id=45).gettext()
    NEXT_UNOCCUPIED_TIME = Template.messages.get(id=46).gettext()
    RESERVATION_TIME_OCCUPIED = Template.messages.get(id=47).gettext()
    RESERVATION_FINISH = Template.messages.get(id=48).gettext()
    DAY_LIMIT_EXCEEDED = Template.messages.get(id=51).gettext()
    RESERVATION_TIME_PAST = Template.messages.get(id=52).gettext()
    RESERVATION_LIMIT_EXCEEDED = Template.messages.get(id=53).gettext()
    RESERVATION_INFO = Template.messages.get(id=54).gettext()
    MY_RESERVATIONS_EMPTY = Template.messages.get(id=55).gettext()
    RESERVATION_REFUSED = Template.messages.get(id=56).gettext()
    REQUEST_CONFIRMATION = Template.messages.get(id=59).gettext()
    REQUEST_CONFIRMATION_ACCEPT = Template.messages.get(id=60).gettext()
    REQUEST_AFTER_VISITING = Template.messages.get(id=66).gettext()


class Keys():
    KEY = Template.keys.get(id=2).gettext()
    SEND_CONTACT = Template.keys.get(id=5).gettext()
    YES = Template.keys.get(id=7).gettext()
    NO = Template.keys.get(id=8).gettext()
    CONTACT_ADMINISTRATOR = Template.keys.get(id=14).gettext()
    CONTACTS = Template.keys.get(id=17).gettext()
    BACK = Template.keys.get(id=22).gettext()
    REFERALS = Template.keys.get(id=23).gettext()
    MENU = Template.keys.get(id=34).gettext()
    RESERVATION = Template.keys.get(id=35).gettext()
    SELECT_REGION = Template.keys.get(id=36).gettext()
    FOR_TODAY = Template.keys.get(id=38).gettext()
    FOR_TOMORROW = Template.keys.get(id=39).gettext()
    FOR_ANOTHER_TIME = Template.keys.get(id=40).gettext()
    CANCEL = Template.keys.get(id=41).gettext()
    MY_RESERVATIONS = Template.keys.get(id=49).gettext()
    SELECT_ANOTHER_DATE = Template.keys.get(id=50).gettext()
    REQUEST_CONFIRMATION_ACCEPT = Template.keys.get(id=57).gettext()
    REQUEST_CONFIRMATION_REFUSE = Template.keys.get(id=58).gettext()
    REQUEST_AFTER_VISITING_OK = Template.keys.get(id=63).gettext()
    REQUEST_AFTER_VISITING_RECEIVING = Template.keys.get(id=64).gettext()
    REQUEST_AFTER_VISITING_IN_QUEUE = Template.keys.get(id=65).gettext()


class Smiles():
    SMILES = Template.smiles.get(id=3).gettext()
    NEXT_PAGE = Template.smiles.get(id=61).gettext()
    PREV_PAGE = Template.smiles.get(id=62).gettext()
