# Generated by Django 4.0.3 on 2022-09-17 10:09

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('address', ckeditor.fields.RichTextField(verbose_name='Адрес')),
                ('working_time_from', models.TimeField(verbose_name='Время работы, от')),
                ('working_time_to', models.TimeField(verbose_name='Время работы, до')),
                ('day_limit', models.PositiveIntegerField(verbose_name='Ограничение на количество людей')),
                ('period', models.PositiveIntegerField(verbose_name='Период(в минутах)')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.AddField(
            model_name='botuser',
            name='first_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='botuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='botuser',
            name='username',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(verbose_name='Дата и время')),
                ('status', models.IntegerField(choices=[(0, 'Refused'), (1, 'In Queue'), (2, 'Receiving'), (3, 'Did Not Come'), (4, 'Ok')], default=1, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='backend.botuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
        migrations.CreateModel(
            name='RegionAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='backend.region')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_admins', to='backend.botuser')),
            ],
        ),
        migrations.AddField(
            model_name='botuser',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='backend.region', verbose_name='Регион'),
        ),
    ]
