# Generated by Django 4.0.3 on 2022-09-18 08:32

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_alter_botuser_first_name_alter_botuser_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='region',
            managers=[
                ('regions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='reservation',
            managers=[
                ('reservations', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='botuser',
            name='temp_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
