# Generated by Django 4.0.3 on 2022-09-18 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_region_managers_alter_reservation_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='timezone',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
