# Generated by Django 4.0.3 on 2022-09-20 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_reservation_created_reservation_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='botuser',
            name='from_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referals', to='backend.botuser'),
        ),
    ]
